apiVersion: v1
kind: ConfigMap
metadata:
  name: fe
data:
  FAIL_ON_ERROR: "1"
  API_ORIGIN: "http://be"
  FONT_COLOR: {{ .Values.FONT_COLOR | quote }}
  BACKGROUND_COLOR: {{ .Values.BACKGROUND_COLOR | quote }}
