apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
spec:
  serviceName: redis
  volumeClaimTemplates:
    - metadata:
        name: redis
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      volumes:
        - name: redis
          persistentVolumeClaim:
            claimName: redis
      initContainers:
        - name: setup-fs
          image: debian:13-slim
          command:
            - /bin/sh
            - -c
            - chown -R 999:999 /data
          volumeMounts:
            - name: redis
              mountPath: /data
      containers:
        - name: main
          image: redis:8
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: redis
              mountPath: /data
          startupProbe:
            tcpSocket:
              port: 6379
          livenessProbe:
            tcpSocket:
              port: 6379
          resources:
            requests:
              cpu: 50m
              memory: 100Mi
            limits:
              memory: 200Mi
              cpu: 200m
